# /opt/rabid-ui/app_utils/art.toml

radioactive = """
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀    ⠀⠀⠀⠀⢀⣀⣀⣤⣤⣤⣤⣤⣤⣤⣼⣷⣿⡿⣿⣭⣥⣁⣁⣀⣁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣴⣶⡿⣿⢿⣟⣿⣻⢾⣽⢯⡿⣽⢯⣷⣟⣾⡽⣿⡽⣯⢿⣻⡿⣟⣿⢿⣷⣶⣦⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣾⡿⣟⣯⡿⣾⣽⣟⡿⣞⣯⣟⣯⡿⣯⣟⣯⣿⢾⣽⣾⣻⢷⣟⣿⣻⣽⣻⣽⢯⣿⣞⣷⢯⣟⡿⣽⡿⣦⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⢴⣿⣟⣿⣳⣿⣻⣽⣻⢷⣷⢾⣻⢿⣽⡾⣯⣟⣷⢿⣽⣾⣻⢷⣯⣟⡿⣾⡽⣷⣻⣽⣮⢿⣳⡿⣾⣻⢯⣟⣯⣿⡽⣯⣿⢿⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣬⢿⣷⢿⣭⣿⢷⣻⣟⣾⣟⣯⣿⢾⣽⣷⣻⡽⣿⣞⡷⡟⣿⢾⣽⣻⢷⣟⣯⡿⣾⣽⣻⢯⣟⣷⢿⣻⢯⣷⢯⣿⣳⣯⡿⣽⣻⢿⣶⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠈⣿⣿⣯⢿⣽⣿⣿⣾⣿⣾⣽⢾⣻⢷⣯⢿⣽⣷⣻⣟⡿⣽⣯⡷⣿⢯⣟⡷⣿⣽⢾⣻⣯⢿⣾⣹⢯⣿⢯⣿⣳⣯⣷⢿⣻⣽⣟⡾⣿⠏⢀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡇⢹⢿⣿⣿⣿⣿⣿⣿⣿⣿⣾⣟⣯⣿⢾⣻⡷⣯⣷⣟⡿⣽⣾⣻⣽⢿⣼⢿⣽⡾⣟⡿⣞⣿⣳⢿⣻⣽⣯⡷⣟⣷⢯⣿⣻⢾⣽⣿⢏⣀⠎⠀⣴⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣷⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⢿⡾⣿⣹⢿⣷⢿⣾⢿⡿⣾⣹⣏⣿⣾⢿⣷⢿⣿⣹⡿⣷⣿⢿⡿⣾⢷⣿⣏⡿⣏⣷⣿⣏⣿⡏⠆⡎⠀⣸⣿⢿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡴⢷⣖⣚⣻⣥⣶⣀⣀⡤⢄⡇⣿⣿⣯⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣟⣯⣿⠿⠾⠛⠛⠛⠛⠛⠛⠛⠛⠛⠿⢾⣿⣾⣽⣻⢷⣯⣿⠝⣿⢯⣷⣻⣽⢿⣽⡾⣽⡟⢨⡝⠀⢠⣿⣯⡿⣽⡿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⡿⠿⠛⠛⠉⠀⠈⠙⠻⢿⣿⣿⡟⢻⠛⠚⠛⠛⠛⠋⠉⠙⠛⠿⢿⣷⣻⣿⡉⡱⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣈⣙⢷⣿⣻⣾⡽⣟⣯⣿⣽⣻⢾⣯⣷⣿⡟⠬⡝⠀⢠⣿⡿⣾⣽⡷⣿⣻⢿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣀⣠⣤⣶⣿⣟⣿⢿⣿⣷⣦⣬⣝⡇⢸⠀⠀⠀⠀⠀⠀⠀⣴⢦⣄⠀⠉⠻⣽⣿⡄⠘⢄⠀⠀⠀⠀⠀⠀⣠⣾⣽⣶⣿⣿⣯⣿⣿⣾⡽⣿⡽⣾⣳⡿⣯⣷⣿⡯⣽⠟⠀⣠⣿⡿⣽⡷⣯⢿⣷⣻⣯⢿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠉⢙⣿⣿⠛⠉⠉⠉⠉⠙⠛⠛⠛⣿⣿⣿⣿⣿⡀⢇⠀⠀⠀⠀⠀⢸⣿⣶⡈⢷⣄⡀⠈⠻⣿⣦⣄⢷⣤⡀⠀⠀⠀⢻⡿⠟⢿⠿⠿⠀⠉⠙⠛⠻⢷⣿⣯⢷⣟⣿⣾⣷⣛⠋⠳⣴⣿⠛⣛⣛⠛⠛⠛⠚⠓⠛⠿⠾⠿⢆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⣰⣶⣶⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⢎⠀⠀⣀⣹⣿⣷⣈⣦⣀⠀⠀⠀⠀⢿⣿⣷⣄⠙⠻⢿⣿⠞⡿⠈⠙⢯⠸⡀⠀⠀⠀⠑⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⢻⣿⢿⣋⠉⡹⠳⡄⣰⣿⣿⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⠂
 ⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠸⠀⠸⡅⠀⢻⣿⣿⠟⠻⣍⠢⡀⠀⠀⠙⠿⣿⣿⣿⣿⢃⡴⠃⣠⣤⠈⣧⠱⡀⠀⠀⠀⠈⠢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢷⠗⠛⠋⠀⠀⣸⣿⡿⣽⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀
 ⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⡆⠀⣇⠀⠀⢿⣎⠂⣼⣿⠷⣌⠢⡀⠀⠀⠀⠙⠿⣿⠋⠁⢴⣾⢁⠆⢼⣆⣱⣶⣒⣠⣴⣶⡢⢄⡀⠀⠀⠀⠀⠀⠀⠀⠈⢧⠀⠀⠀⢰⣿⡿⣽⡿⣶⣶⣶⡶⣴⣤⣤⣤⡌⢹⣿⣿⣿⣿⡇⣦⠀⠀⠀⠀⠀⠉⠉⠀⠀
 ⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⢱⠀⢹⠀⠀⠘⣷⣸⣿⢞⢧⠈⢧⠀⠀⠀⠀⠀⠀⠈⠙⠲⠬⠴⠽⠞⠛⠋⠉⠉⠀⠀⠀⠀⢙⡦⣸⢻⣤⣱⡶⢄⣀⣀⡀⡀⠳⡄⢠⣿⣿⣻⣽⣻⡷⠿⠾⠽⠿⠯⠿⠿⡇⢸⣿⣿⣿⣿⡇⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⡄⠘⡆⠀⠀⢹⣿⣿⡵⢚⣆⠀⢳⡀⠀⠀⠀⠀⠀⠀⠀⢠⡔⠛⠓⠦⣄⠉⠒⠒⠀⡤⣊⠁⠀⠈⢻⣿⡟⠙⢦⣍⡓⢬⡁⠀⠘⢾⣿⣳⣟⡷⣿⡀⢶⣶⣶⣶⣶⣤⣴⣶⣾⣿⣿⣿⣿⣧⣤⣤⣤⣤⣤⣤⣤⣤⡄⠀
 ⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢇⠀⣷⠀⠀⠀⢻⣏⠞⠡⠈⣀⠤⢷⡀⠡⡀⠀⠀⠀⠀⠀⠉⠳⣤⡀⠀⠙⠢⣄⡜⠀⡟⢀⠀⠸⠉⠛⠻⣦⣀⣸⣿⣄⡷⠤⣄⣸⣿⣽⡾⣿⡽⣷⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀
 ⠀⢰⣿⣿⣿⣿⣿⣿⣿⠿⣿⢄⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⢸⡀⠀⠀⠘⡿⣯⠉⠉⠀⡀⡀⢷⣄⠘⠢⡀⢀⡠⠔⠊⠉⠀⠉⠓⢶⡉⠉⠙⠢⣙⣍⡑⠠⢄⣀⣠⠞⠛⠺⠛⠛⠛⠒⠒⠾⣿⣳⣿⣳⣿⣻⢷⣶⡶⣶⢦⣶⡤⢰⣿⣿⣿⣿⣿⣿⣆⢴⣦⡄⠀⠈⠀⠉⠀⠀
 ⠀⣿⡿⡽⡱⡡⡳⠁⢀⡴⠃⠀⠀⠀⠉⠁⠀⠀⠀⠀⠀⣀⠈⡆⠈⣇⠀⠀⠀⢹⢿⣇⠀⠀⣥⡒⢺⣿⣳⣤⡚⠁⠢⢄⡀⠀⠀⠀⠀⠀⠉⢲⡤⠀⠒⣳⡉⠲⣤⠎⣀⣉⠉⣁⢀⠀⣉⣈⣉⣉⣉⢻⣷⣟⣞⣯⣿⢾⣽⣯⢿⡽⢁⣿⣿⣿⣿⣿⣿⣿⣿⣧⣹⢿⠀⠀⠀⠀⠀⠀
 ⢐⣿⢎⢜⢌⠜⡐⢡⠞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡴⠋⠀⠀⣿⡄⠀⠀⣸⣸⡟⠀⠀⠀⢉⣹⣯⡷⢿⡿⣶⣄⡀⠈⠀⠀⠀⠐⠒⠒⠚⠉⠙⠿⡉⣙⣾⡟⢳⢤⣀⣀⣀⣠⣴⠶⠓⣦⣀⣠⣿⡿⣞⣿⣽⢾⣟⡷⣯⡟⢡⣾⣿⣿⣿⠏⣌⠻⣿⣿⣿⣿⣶⣅⠀⠀⠀⠀⠀
 ⠰⢡⢊⡪⢂⠎⣰⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠔⠉⠀⠀⠀⣴⣿⠇⢀⡼⣵⡟⠀⠀⣀⣴⣿⣿⣭⣙⣛⣛⣛⣿⣿⢷⣒⡶⠤⠤⣄⣀⣀⣤⡴⣚⡿⣿⣿⣧⢇⣾⣿⢿⡿⣯⢿⡀⢰⣽⡿⣟⣯⢿⣻⢷⣯⡿⣾⡿⢋⣰⣿⣿⣿⣿⠏⣼⡿⣷⣌⠻⣿⣿⣿⣿⣷⣄⡀⠀⠀
 ⡔⡵⡑⡡⢃⣴⠏⠒⠠⢄⡀⠀⠀⠀⠀⠀⣠⠔⠁⠀⠀⠀⢠⣾⡿⠃⢠⢾⣿⣅⡀⣠⣾⣿⣿⡿⣯⣭⣽⡿⣿⣿⣿⣷⣿⣿⣷⣤⣴⣏⣛⣋⣡⣾⡿⢠⢻⣿⣿⣿⣿⣯⡿⣽⣿⣯⣛⣚⣾⣿⣻⣽⣟⣯⣿⡾⠛⣉⣴⣿⣿⣿⣿⡿⢁⣾⡿⣽⣷⣻⢷⣌⠛⢿⣿⣿⣿⣿⣶⡄
⢸⣾⣶⣶⣿⣿⣿⡆⠀⠀⠀⠀⠉⠒⠀⠤⠚⠁⠀⠀⠀⢀⣴⣿⠟⠀⣴⣻⢟⢿⣿⣿⣿⣯⣿⣿⣿⣷⣿⣿⣿⣿⠟⣿⣿⣿⢻⣿⠃⠸⣟⣽⣿⡽⣿⣇⣸⣿⣿⣿⡏⣼⡿⣽⣟⣾⣟⡿⣟⣿⣳⡿⣿⣽⣳⣿⡀⣿⣿⣿⣿⣿⠟⢃⣴⣿⢯⣟⣷⣯⣟⣯⡿⣿⣦⡙⠻⣿⡿⠋⠀
⢸⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⠏⠀⡾⡿⢿⣷⡏⣾⣏⣾⣿⣿⣿⣿⣿⣿⣿⡏⠉⠀⢸⣷⣾⣿⣿⠀⠀⣿⢿⡸⣿⠀⠀⡾⣸⣿⣿⣿⣹⣿⣏⡿⣷⣏⣿⢿⠿⣏⡿⣷⣏⡿⣾⡇⢹⣿⠿⠏⢁⣾⣿⣿⣹⣏⣿⡏⣷⣿⣹⢿⣷⢿⣿⠀⠀⠀⠀⠀
⢸⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⢒⢺⢹⣥⠈⢻⣿⣿⣿⣿⣿⠿⠛⠁⣸⣿⡿⠁⠀⠀⠈⠧⡙⢿⣽⣦⠀⠘⢆⢳⠹⣆⣸⣡⡿⢟⣿⣿⣫⣿⣯⢿⣳⡿⣽⣻⡏⣭⡕⣿⣯⢿⣻⣷⣤⣤⣴⣾⢿⣯⣷⢯⣷⡿⣾⣟⣿⣳⢿⣻⡾⣟⣿⠀⠀⠀⠀⠀
⢸⢸⣿⣿⣿⣿⣿⣿⣷⣶⣒⣒⣶⡶⠂⠀⠀⠀⠀⠈⣿⣿⣷⠀⢼⢸⢺⡀⠸⣿⣿⣿⡻⠁⠀⠀⢀⣿⡟⠁⠀⠀⠀⠀⠀⠘⣆⢻⣽⣧⡀⠀⠈⣆⣏⣿⣿⡟⢸⣸⣿⣿⣷⣿⣿⢯⣟⡿⣽⣾⡿⢿⡿⣽⣻⡷⣯⢿⣽⣳⣯⣿⣾⣽⣻⢷⣻⣟⣾⣷⣻⠿⠽⠿⢽⣿⠀⠀⠀⠀⠀
⢸⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢫⠁⠀⠀⠀⠀⠀⠀⢸⣿⣿⠄⢸⢸⢸⡇⠀⣿⣿⠇⠀⠀⠀⠀⢸⣿⡅⠀⠀⠀⠀⠀⠀⠀⠘⣄⣻⣽⣿⢻⣟⣷⣿⡞⢻⣧⠞⢫⣻⣿⣿⣻⣿⣯⡿⣽⣿⡙⠿⢨⣽⣿⢷⣿⣻⢯⡟⢰⣦⣤⣤⠄⠿⠟⠻⠾⠿⠀⣶⣶⣶⣶⡆⠁⠀⠀⠀⠀⡀
 ⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣸⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⡦⠀⣿⢸⡃⠀⣿⣿⠅⠀⠀⠀⠀⠈⢿⣿⡆⠀⠀⠀⣾⣿⣞⠩⠙⣫⣥⣷⣿⣯⣉⠩⣻⠀⠁⠀⠀⡇⣿⢿⠧⡰⣿⣿⣽⢾⣿⢿⣾⣾⢿⣻⣷⣻⣿⠁⣾⣿⣿⣿⣶⣾⣿⣶⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣗
 ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠸⣿⣇⠢⣿⡇⠀⠀⣿⣿⣀⣠⡄⠀⠀⠀⣸⡿⠁⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⡽⣯⢿⣿⣿⣿⣷⣶⣤⠀⢻⣿⣧⠉⠁⣿⡷⣯⣿⣬⠽⢸⣯⢿⣻⣞⣷⡏⣰⣿⣿⣿⠿⠿⠿⠿⠿⠿⠿⠿⢿⣿⣿⣿⡿⠛⠛⠛⠛⠛⠋
 ⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⢿⣿⡑⣿⡇⠀⢠⣿⣯⢟⡽⠁⠀⠀⢠⡿⠁⠀⠀⠀⠀⢀⣿⣿⣿⣶⡌⢹⣿⣟⣯⡿⣟⡿⣿⣿⢹⣇⠀⢿⠻⣧⣠⣿⡿⣽⣾⣿⢷⣾⣟⣿⣽⣻⡞⢠⣿⣿⣿⣯⢰⠀⣤⣤⣤⣤⣤⣤⣼⣿⣿⣿⣷⣤⣤⣤⣤⣤⡄
 ⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠸⣿⡢⣿⡇⠀⣿⣉⣤⠾⠁⠀⠀⠀⣾⠇⠀⠀⣤⣾⣿⣿⣿⣿⣿⣿⣷⠈⣿⣯⣷⢿⣻⣽⣟⣿⡇⢻⡄⠸⡇⠀⣹⣿⡽⣟⣾⣎⢿⣵⣿⣻⣞⡟⢠⣿⣿⣿⣿⣿⠰⠀⣿⣿⣿⣿⡿⣿⣿⣿⣿⣿⣿⠿⠿⣿⣿⣿⣇
 ⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⢿⡮⣺⢷⠀⠙⣿⣧⡀⠀⠀⠀⣸⡟⠀⢀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⢿⣿⡽⣿⣾⣟⣾⣻⣿⡀⠃⠀⠠⣞⣿⡿⣽⣟⣷⣻⢷⣼⡷⣟⠟⣠⣿⣿⣿⣿⣿⣿⢸⠀⣿⣿⣿⠀⣤⣄⢸⣿⣿⣿⡇⠀⠀⣿⣿⣿⣷
 ⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠈⡿⣾⢸⠀⠀⠈⢿⣧⠀⠀⢀⣿⠁⢀⣞⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠘⣿⣿⣳⣟⣾⡽⣷⢿⣇⠀⠀⢸⡗⢸⣿⣟⣾⢿⡙⠷⢨⣽⣿⡄⢻⣿⣿⣿⣿⣿⣏⢸⠀⣿⣿⣿⣤⣤⣴⣾⣿⣿⣿⣷⣶⣶⣿⣿⣿⣿
 ⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢧⠀⠀⠀⠀⠀⠀⠀⣈⡥⠏⠀⠀⠀⠀⠙⣷⣄⣸⣏⣠⣿⡼⡄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⢹⣿⣟⣾⢯⣿⡽⣿⢿⡆⠀⢸⡷⢸⣿⣟⣾⢿⣻⣿⣼⣽⣟⣿⡌⢿⠏⣿⣿⣿⡷⢸⡄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
 ⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣿⣿⢻⡿⣺⡆⠀⠀⢀⣠⠴⡾⣭⣲⣄⡀⠀⠀⠀⠀⢹⣿⣿⠟⣹⡏⣿⡄⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠘⣿⣿⣞⣿⣳⣿⢯⣿⣷⠀⢸⣟⠀⣿⣿⣞⣿⢻⣭⣭⣽⣟⡾⣿⣤⠀⣿⣿⣿⡇⣸⣷⠖⠀⣀⣤⡀⢠⣿⣿⣿⣿⠇⠀⠀⣿⣿⣿⣿
 ⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⠋⢸⢧⣵⡿⣶⣾⣯⢯⡞⠀⠌⠪⡙⢿⣿⣲⡀⣀⣼⣿⣫⣼⡿⢠⢻⣜⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢻⣿⡾⣯⢿⡾⣿⣽⣻⡇⢸⣿⣤⢻⣷⣯⢿⣷⣶⣶⣿⢯⡿⣷⢿⠀⣿⣿⣿⡇⣿⣷⡀⢿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣿⡿⠀⡾⢰⠛⢒⣿⣿⣯⣇⣁⢰⡆⡀⢱⠀⠀⠉⠻⣾⡿⣿⣿⣿⠃⡸⡼⠛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠸⣿⣿⡽⣿⡽⣷⢯⣿⣿⣼⣿⣿⠎⣿⣯⣿⢣⡹⠼⣯⣿⣻⣽⣿⠀⣿⣿⣿⡇⣿⠟⠛⣀⣽⣿⣿⣿⣿⣿⣿⣶⣤⣤⣄⣀⡀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⠃⠀⡇⣸⠈⢸⢿⣿⢻⠿⠿⣾⣥⢿⡄⡇⠀⠀⠀⢻⡶⣻⣿⡏⢀⡇⡧⣰⢫⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢿⣿⣟⡷⣿⢯⣿⣳⣟⡿⣿⣦⣾⣿⣳⡿⣟⣿⣸⣿⣳⣿⣳⣿⠀⣿⣿⣿⡇⣧⢸⣿⣿⣿⣿⣿⣿⠟⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⠀⡇⣇⡇⠀⣸⣞⣄⡿⠀⠀⠀⠀⠉⡻⣷⠀⠀⠀⠘⣷⣿⣿⡆⣸⢸⣵⢻⣷⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢃⣼⣿⡿⣽⣻⣯⡷⣿⣽⣻⢷⣻⡷⣯⣷⢿⡝⣿⣋⣿⢷⣯⡷⣿⠨⣿⣿⣿⡇⣿⡀⠿⠿⠟⠛⠉⠀⠀⠀⠀⠀⠉⠙⠛⠛⠛⠿⠿
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠳⠏⢀⡜⠁⠀⠀⠉⠉⠐⠒⢤⣀⡇⠹⣆⠀⠀⠀⠸⣿⣿⡾⢃⣿⣿⠛⢹⠑⡿⣿⣿⣿⣿⣿⣿⣿⢋⣴⣿⣿⣿⣻⣽⢷⣯⢿⣳⣯⣟⢿⣽⣻⢷⣯⣿⣻⣬⣻⣟⡿⣾⣽⢿⣄⣉⣥⣤⣥⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⡀⠀⢀⣀⠀⠀⣾⣿⣿⢸⡀⠸⣶⡀⠀⠀⠀⠀⢀⣾⣿⣿⣶⢸⡀⠸⣹⣿⣿⣿⣿⡿⣱⣿⣿⡿⣿⣾⣹⣏⣿⣾⡿⣏⣷⣿⢾⣷⢿⡿⣾⣷⢿⣹⢿⣾⡿⣷⣏⣿⣏⡿⣏⣿⣹⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠿⣿⣿⡇⠘⠿⠿⠋⠀⢷⣠⡽⣿⣷⣤⡀⣀⣾⠟⢡⣿⣳⣿⣧⢀⣧⣿⣿⡿⠋⣾⣿⣿⢯⣟⣷⣯⡷⣿⡽⣾⣽⣟⡷⣯⣿⢾⡿⣽⣟⣾⣟⣯⣿⢾⣽⣫⣿⢾⣽⣻⣯⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠙⠻⢦⣤⣀⣤⡈⠑⠢⠼⠧⢼⣿⣿⡧⠀⢀⣽⣿⣿⣿⠁⢸⢼⣿⠁⣸⣿⣿⣽⣻⣟⣾⣳⡿⣽⣻⣼⡷⣯⣿⣻⢾⣻⠽⣟⣾⢷⣯⣟⣾⢿⣽⣳⣯⣿⠷⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠂⡞⣿⡿⠀⠀⠀⠀⠀⢀⣿⡿⡡⣠⣿⣿⣿⣿⡇⠀⢸⢸⡷⢠⣿⣿⣳⣯⡷⣟⣷⢿⣽⢿⣽⣳⣿⣻⢾⣽⣟⡿⣶⣟⣯⡿⣾⡽⣯⣿⣞⡯⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠻⠁⠀⠀⠀⠀⣠⣿⣿⠟⣴⣿⣿⣿⣿⡿⠀⣀⣸⣸⠇⣾⣿⢷⣻⢷⢛⡿⣽⣻⡾⣯⣷⣟⣷⣻⣯⡷⣿⡽⣷⣯⢿⣽⡷⣿⠟⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⠿⠛⣡⣾⣿⣿⣿⣿⣿⠋⠁⣠⢋⣿⣻⣿⣿⣻⢯⣿⣻⢿⡽⣷⣟⡿⣾⣽⢾⣻⣾⡽⣷⢿⣻⡾⠟⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠛⠁⠀⠙⣚⣵⣿⣿⣿⣿⢷⣻⣟⡷⣿⢯⡿⣷⣻⣽⡷⣯⣿⣷⡯⠿⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                                                     ⣉⠛⢛⢛⡋⡟⣿⢿⡿⣾⡿⣽⣿⣟⠛⡛
"""

biohazard = """
       ...
     ."   ".
 .--.       .--.
(    \\     /    )
 \\    \\   /    /
  \\    \\ /    /
   \\    "    /
    \\       /
     |     |
    /       \\
   /    "    \\
  /    / \\    \\
 /    /   \\    \\
(    /     \\    )
 "--"       "--"
"""
